[versions]
kotlin = "2.0.21"
compose = "1.6.7"
android-gradle = "8.4.0"
material3 = "1.4.0"
ui-tooling-preview = "1.10.1"
ui-tooling = "1.10.1"
navigation-runtime-ktx = "2.9.6"
navigation-compose = "2.9.6"
lifecycle-runtime-ktx = "2.10.0"
compose-bom = "2024.09.00"
lifecycle-viewmodel-ktx = "2.10.0"
runtime-livedata = "1.10.1"
activity = "1.12.3"

[plugins]
android-application = { id = "com.android.application", version = "8.6.0" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version = "2.0.21" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version = "2.0.0" }

[libraries]
androidx-core-ktx = "androidx.core:core-ktx:1.13.1"
androidx-appcompat = "androidx.appcompat:appcompat:1.6.1"
material = "com.google.android.material:material:1.11.0"
androidx-activity = "androidx.activity:activity-ktx:1.9.0"
androidx-activity-compose = "androidx.activity:activity-compose:1.9.0"
androidx-ui = "androidx.compose.ui:ui:1.6.7"
androidx-material = "androidx.compose.material:material:1.6.7"
androidx-ui-tooling-preview = "androidx.compose.ui:ui-tooling-preview:1.6.7"
androidx-ui-tooling = "androidx.compose.ui:ui-tooling:1.6.7"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.4"
junit = "junit:junit:4.13.2"
androidx-junit = "androidx.test.ext:junit:1.1.5"
androidx-espresso-core = "androidx.test.espresso:espresso-core:3.5.1"
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "ui-tooling-preview" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "ui-tooling" }
androidx-navigation-runtime-ktx = { group = "androidx.navigation", name = "navigation-runtime-ktx", version.ref = "navigation-runtime-ktx" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle-viewmodel-ktx" }
androidx-compose-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "runtime-livedata" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
